### ISSUE TITLE
Technical difficulties in CiviCRM 4.6.20, Joomla.

### ISSUE THREAD

**Issue by mrojassoto** [TechToThePeople/publicautocomplete#10]
I am on CiviCRM 4.6.20, trying this extension for the first time, and I am in Joomla 3.6.5. I installed version 1.4 and enabled it.  Then I added this to my civicrm.settings.php file:

global $civicrm_setting;
$civicrm_setting['eu.tttp.publicautocomplete']['params'] = array(
'contact_type' => 'Organization',
'return' => 'display_name'
);
$civicrm_setting['eu.tttp.publicautocomplete']['match_column'] = 'organization_name';

I am not filtering by any groups, or contact sub-types. When I try to use my event sign up forms, I see the regular open-entry text field.  When I go to the public form, I get an open-entry text field as well.

What am I missing?  Thanks.

**Comment by mrojassoto** [comment]
Update on my end:

I migrated to 4.7.14, Joomla 3.6.5.  I added this to my civicrm.settings.php file in:
public_html/administrator/components/com_civicrm/
and in public_html/components/com_civicrm/

 global $civicrm_setting;
 $civicrm_setting['eu.tttp.publicautocomplete']['params'] = array(
  'contact_type' => 'Organization',
  'group' => 93, // members of the Public Auto Complete Organizations Group
  'return' => 'display_name'
);

 $civicrm_setting['eu.tttp.publicautocomplete']['match_column'] = 'sort_name';

When I test it, I still see the open-entry text field.
Thanks.

**Comment by twomice** [comment]
Hi @mrojassoto . By "open-entry text field," I guess you mean there's no autocomplete at all, just a plain text field -- right? Here are a couple of things you could check:

* Have you followed the steps in "Test, and Access rights" in the README? (I.e., are you signed in as a user with access to CiviCRM?)
* Are there javascript errors on the page? (For example, in chrome: right-click anywhere on the page, click "Inspect" and observe the developer tools pane at the bottom of the page, then click the "Console" tab in that pane to see any Javascript errors. In firefox, try Ctrl + Shift + J to display the JavaScript console.)

Thanks!

**Comment by mrojassoto** [comment]
Thanks @twomice for your help.  I did what you suggested, and it turns out the extension wasn't loading at all.  I edited the .htaccess file, and now it works perfectly.  Great to have this working to prevent so many duplicate organizations in my database.
Best regards!

**Comment by twomice** [comment]
Glad to hear it @mrojassoto. Thanks for reporting back!
