### ISSUE TITLE
Version 1.4 breaks on CiviCRM 4.4

### ISSUE THREAD

**Issue by ddoligalski** [TechToThePeople/publicautocomplete#11]
Version 1.4 adds functionality that implements "accept_existing_value". 

The underlying code calls, `CRM_Core_Session::getLoggedInContactID`which does not exist in CiviCRM 4.4. In 4.4, the function is located in `CRM_Core_Form::getLoggedInContactID`.

The workaround is to set `accept_existing_value=FALSE`.

**Comment by tttp** [comment]
I'll close that one, assuming compatibility with civicrm 4.4 isn't a big concern right now ;)
