### ISSUE TITLE
Auto complete not working on some ajax forms

### ISSUE THREAD

**Issue by lunarstack1** [TechToThePeople/publicautocomplete#22]
Steps in CiviCRM:

Create a new case in CiviCRM
Under the Role tab on the case, click to assign a person to a role.
Select the role, and then select to add new contact with employer field present.
The auto complete field does not complete.

Solution: Remove the load order from the JS and this fixes the issue.
https://github.com/devappau/publicautocomplete/commit/005da82b4e63523a2dd94f07916c2933cdaf7f93 

Can this be merged?

**Comment by twomice** [comment]
Hi @adam-devapp Would you mind creating a PR for this change? Should be fairly easy for us to test and then merge.

**Comment by twomice** [comment]
(Thanks for the report and the solution, BTW.)

**Comment by lunarstack1** [comment]
All done.

**Comment by lucky091588** [comment]
Hi @adam-devapp, I can't seem to reproduce this error in civicrm v5.29.1.

Can you provide more specific steps?
Also, what version of civicrm are you running?
Does the case client need to be Organization or Individual?

**Comment by lunarstack1** [comment]
Running 5.34.0. Happened on 5.29.1 too.

Photos attached. 

Note: We have inserted additional contact options options using hooks to profile forms, however any form with the employer field present should have issues without the patch. In theory, any profile form in AJAX should do the same thing.

<img width="915" alt="step 1" src="https://user-images.githubusercontent.com/13082954/108933758-9cf14c80-769b-11eb-8e17-b71ea321716e.png">
<img width="976" alt="step 2" src="https://user-images.githubusercontent.com/13082954/108933761-9ebb1000-769b-11eb-9301-036d086e0a5a.png">

**Comment by lucky091588** [comment]
Hey @adam-devapp, I tried the fixed you submit, but I found a bug on it. In drupal 7, if you go to `http://yoursite/user/`, click edit and be sure that the employer field exist on the form edit page. The autocomplete will not work. That is why, I added another fix (https://github.com/TechToThePeople/publicautocomplete/pull/24) for this which will work on every form page that has employer field. I hope it helps.

**Comment by lunarstack1** [comment]
I've tested on a normal profile form and also one with AJAX (case -> roles -> profile with employer) and both worked with the changes you made. Thank you for the change! Looks good to merge.

<img width="1037" alt="Screen Shot 2021-02-28 at 8 47 36 pm" src="https://user-images.githubusercontent.com/13082954/109415035-3c993c80-7a06-11eb-916d-20253a0f22c2.png">

**Comment by twomice** [comment]
Fixed in #24 / 9bb2add. Thanks @lucky091588 and @adam-devapp !
