### ISSUE TITLE
Not working on additional participant registration page

### ISSUE THREAD

**Issue by sunnycs121** [TechToThePeople/publicautocomplete#26]
Hi,

Organization field (field name current_employer) is not showing autopopulate options additional participant registration page. Field do not have class "ui-autocomplete-input".

Hassan

**Comment by sunnycs121** [comment]
Adding `CRM_Event_Form_Registration_AdditionalParticipant` in returned array in function `_publicautocomplete_supported_forms` of file `publicautocomplete.php` worked for me.

**Comment by twomice** [comment]
Thanks @sunnycs121 , good find, and that sounds like a reasonable fix. Are you able to make a Pull Request for this fix?

**Comment by sunnycs121** [comment]
Thanks @twomice, just created [pull request](https://github.com/TechToThePeople/publicautocomplete/pull/27), please review.

**Comment by webmaster-cses-org-uk** [comment]
I've been meaning to report this for a while but see that someone has beaten me to it!

+1 👍  for reporting and +1 👍  for the fix. I was going to suggest exactly the same (adding form name to _publicautocomplete_supported_forms).

Thanks all :)

**Comment by twomice** [comment]
Fixed in PR #27.
