### ISSUE TITLE
Set minimum matching characters to show organizations

### ISSUE THREAD

**Issue by Detsieber** [TechToThePeople/publicautocomplete#33]
Feature request: 

Currently, one can see all the organisations, simply by entering "%" or " ".
This is legally allowed (since GDPR is not applicable for organisations), however it's somewhat creepy to publish all the organisations you cooperate with.

It would be nice, if we could define a mininum length of a string (e.g. 3 characters), until the search is starting.

**Comment by twomice** [comment]
That's not a bad idea. Thanks for the suggestion @Detsieber .  Perhaps something like `min_length` under [Other config options](]https://github.com/TechToThePeople/publicautocomplete#other-config-options) would be a good place to set this. 

I'd certainly welcome a PR to add this functionality, or would be open to a paid project to do it for you (probably 1-2 hours).

**Comment by alexmarketaccess** [comment]
I would like to upvote on this idea!

**Comment by twomice** [comment]
@Detsieber and others: we've got a new branch for this now at https://github.com/TechToThePeople/publicautocomplete/tree/33_min_length Would you mind testing this and report your findings here ?

**Comment by twomice** [comment]
Fixed in bbdeb6f9ddb8a346f50280d7b9ae78ab1929a4e7 Thanks to @Detsieber for sponsoring the improvement!

(This improvement is included in v1.6.3)
