### ISSUE TITLE
Tag 1.6.1?

### ISSUE THREAD

**Issue by agileware-justin** [TechToThePeople/publicautocomplete#34]
Would be handy if you could tag the latest release, which looks like 1.6.1 from https://github.com/TechToThePeople/publicautocomplete/commit/09046b943cd3d9746d5583088f77016cb0f97cbe

**Comment by twomice** [comment]
Thanks,  I had forgotten to push that tag.

**Comment by agileware-justin** [comment]
Thanks @twomice
