### ISSUE TITLE
Possible error in https://github.com/TechToThePeople/publicautocomplete/blob/master/README.md

### ISSUE THREAD

**Issue by chaplincircle** [TechToThePeople/publicautocomplete#39]
The readme.md refers to 

You need to add in your civicrm.settings.php a new config variable

global $civicrm_setting;
$civicrm_setting['eu.tttp.publicautocomplete']['params'] = array(
  'contact_type' => 'Organization',
  'contact_sub_type' => 'members',
  'group' => 42, // active groups
  'return' => 'display_name, city'
);

ie Organization with a 'z'

On the site I was adding this to, on civicrm/admin/options/subtype?reset=1 its
Organisation with a 's'

Is this going prevent correct configuration if users copy and paste?

**Comment by pradpnayak** [comment]
I believe the machine name is set with 'z' so it should be with a 'z' in a setting

**Comment by twomice** [comment]
i agree with @pradpnayak : "organisation" is the localized form based on your language selection (or possibly even Word Replacements). Instead of that, you'd want to use the civicrm native machine name for this entity, "organization".

Please let us know how it goes @chaplincircle !

**Comment by twomice** [comment]
Older ticket with no recent feedback. Closing now, with the assumption that the given advice was sound. OP, please feel free to re-open if you're still having this problem.
