### ISSUE TITLE
Wordpress ajax requests being made to wp-admin/admin.php

### ISSUE THREAD

**Issue by studiorepublic** [TechToThePeople/publicautocomplete#45]
Hi,
The plugin looks to be working correctly, but the Ajax requests are being made to wp-admin/admin.php which triggers a 302 redirect to wp-login. Works fine for logged in WordPress users, but not for anonymous users. Is there a workaround for this?

**Comment by twomice** [comment]
Thanks for reporting. Can you also tell what version of the extension, civicrm, and WordPress you're running?

**Comment by studiorepublic** [comment]
Thanks for replying so quickly!
We're on
WordPress 6.0.1
Civi 5.46.3
Extension 1.6.3

**Comment by jaapjansma** [comment]
This is caused by the fact that the extension makes use of the Javascript API function `CRM.api3` from CiviCRM itself. That one has hardcoded the url `civicrm/ajax/rest`. (See here for the line causing this: https://github.com/civicrm/civicrm-core/blob/master/js/crm.ajax.js#L121)

I am not sure on how to change this easily.

**Comment by mlutfy** [comment]
@studiorepublic Can you try giving the `access ajax api` permission to anonymous users?

I had a look at the Stripe extension, which requires the ajax rest api, and it also does a `CRM.api3`, so I believe this is the recommended way.

The permission  is a gate-keeper for extra safety. Permissions of the user are still validated, so they cannot use other API function (access contact information), but it does open the attack surface.

**Comment by jaapjansma** [comment]
I have set that permission and it still does use the backend url for the API call.

**Comment by Detsieber** [comment]
We should continue working with this issue!

1) This is a duplicate: #40 #41 #42 #45 #46 are all about the same thing!

**Comment by jaapjansma** [comment]
I have created a fix for this and a pull request: #47

**Comment by twomice** [comment]
Fixed in #47, to be released within 24 hours under v1.6.4. Thanks @tttp, @jaapjansma, and @studiorepublic !
