### ISSUE TITLE
require_match can prevent user from submitting the existing value

### ISSUE THREAD

**Issue by twomice** [TechToThePeople/publicautocomplete#7]
The require_match option can cause users to be unable to submit a profile without deleting their employee relationship.
### Given configuration:
- $civicrm_setting['eu.tttp.publicautocomplete']['require_match'] is TRUE.
- Alice's currently employer is "Northern Widgets" which is not an organization that fits criteria defined in  $civicrm_setting['eu.tttp.publicautocomplete']['params']. 
### User actions:

When Alice opens the profile "Northern Widgets" appears in the Current Employer field.  Alice makes no changes to the Current Employer field, but changes some other fields in the form, and clicks Submit.
### Resulting behavior:

Alice gets an error message saying that the submitted Current Employer value is invalid. Alice cannot submit the form successfully unless she deletes the Current Employer field value.
### Desired improvement:

By default, the validation should allow Alice to leave the existing Current Employer field value unchanged, even if the employer doesn't meet the configured criteria in $civicrm_setting['eu.tttp.publicautocomplete']['params']. 
As an option, site admins should be able to configure the site to function with the above-described "Resulting behavior" (so Alice can't submit the form with her existing Current Employer value).

**Comment by twomice** [comment]
@tttp Any thoughts on making this the default behavior?

**Comment by tttp** [comment]
If Alice works for a 'locked' organisation, should she be able to change her employee? Can you check with your user if it wouldn't be better to put the field read only? 

In any case, forcing to update the employee is the wrong default indeed

**Comment by twomice** [comment]
Alice could move from a "disallowed" employer to an "allowed" employer, in which case she should be able to record that fact using this field.  If we make it read-only, she can't do that.

**Comment by twomice** [comment]
@tttp I'm inclined to commit this patch and cut a release, in the next few days. Want to talk me out of it?

**Comment by tttp** [comment]
Go for it!

**Comment by twomice** [comment]
Fixed in afdea2c03115df137ad1d48263f0741c0e6fec36
